packages:
  - 'packages/*'
  # 排除测试目录中的包
  - '!**/test/**'
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true

#linkWorkspacePackages: true
